// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "liblvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Autonomous_Mode_Select
void ui_Autonomous_Mode_Select_screen_init(void);
extern lv_obj_t *ui_Autonomous_Mode_Select;
void ui_event_Left_Button( lv_event_t * e);
extern lv_obj_t *ui_Left_Button;
extern lv_obj_t *ui_Left;
void ui_event_Right_Button( lv_event_t * e);
extern lv_obj_t *ui_Right_Button;
extern lv_obj_t *ui_Right;
void ui_event_Skills_Button( lv_event_t * e);
extern lv_obj_t *ui_Skills_Button;
extern lv_obj_t *ui_Skills;
void ui_event_WPRight( lv_event_t * e);
extern lv_obj_t *ui_WPRight;
extern lv_obj_t *ui_WPRight1;
void ui_event_WPLeft( lv_event_t * e);
extern lv_obj_t *ui_WPLeft;
extern lv_obj_t *ui_WPLeft1;
// SCREEN: ui_Selected_Left
void ui_Selected_Left_screen_init(void);
extern lv_obj_t *ui_Selected_Left;
extern lv_obj_t *ui_Left1;
void ui_event_Back_Button( lv_event_t * e);
extern lv_obj_t *ui_Back_Button;
extern lv_obj_t *ui_Back_Button_Label;
// SCREEN: ui_Selected_Right
void ui_Selected_Right_screen_init(void);
extern lv_obj_t *ui_Selected_Right;
extern lv_obj_t *ui_Right1;
void ui_event_Back_Button1( lv_event_t * e);
extern lv_obj_t *ui_Back_Button1;
extern lv_obj_t *ui_Back_Button_Label1;
// SCREEN: ui_Selected_Skills
void ui_Selected_Skills_screen_init(void);
extern lv_obj_t *ui_Selected_Skills;
extern lv_obj_t *ui_Skills2;
void ui_event_Back_Button2( lv_event_t * e);
extern lv_obj_t *ui_Back_Button2;
extern lv_obj_t *ui_Back_Button_Label2;
// SCREEN: ui_Selected_WP_Left
void ui_Selected_WP_Left_screen_init(void);
extern lv_obj_t *ui_Selected_WP_Left;
extern lv_obj_t *ui_Left2;
void ui_event_Back_Button3( lv_event_t * e);
extern lv_obj_t *ui_Back_Button3;
extern lv_obj_t *ui_Back_Button_Label3;
// SCREEN: ui_Selected_WP_Right
void ui_Selected_WP_Right_screen_init(void);
extern lv_obj_t *ui_Selected_WP_Right;
extern lv_obj_t *ui_Left3;
void ui_event_Back_Button4( lv_event_t * e);
extern lv_obj_t *ui_Back_Button4;
extern lv_obj_t *ui_Back_Button_Label4;
extern lv_obj_t *ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
