// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "../../auton/auton.hpp"

void setAutonLeft(lv_event_t * e)
{
	setAutonMode(MATCH_LEFT);
}

void setAutonRight(lv_event_t * e)
{
	setAutonMode(MATCH_RIGHT);
}

void setAutonSkills(lv_event_t * e)
{
	setAutonMode(SKILLS);
}
