// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void setAutonLeft(lv_event_t * e);
void setAutonRight(lv_event_t * e);
void setAutonSkills(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
