// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/field.png
   const char *ui_img_field_png = "S:/usd/assets/field.png";
