// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Selected_Left_screen_init(void)
{
ui_Selected_Left = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Selected_Left, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Left1 = lv_label_create(ui_Selected_Left);
lv_obj_set_width( ui_Left1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Left1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Left1, 0 );
lv_obj_set_y( ui_Left1, -24 );
lv_obj_set_align( ui_Left1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Left1,"Left Auton Selected");

ui_Back_Button = lv_btn_create(ui_Selected_Left);
lv_obj_set_width( ui_Back_Button, 100);
lv_obj_set_height( ui_Back_Button, 50);
lv_obj_set_x( ui_Back_Button, 0 );
lv_obj_set_y( ui_Back_Button, 24 );
lv_obj_set_align( ui_Back_Button, LV_ALIGN_CENTER );

ui_Back_Button_Label = lv_label_create(ui_Back_Button);
lv_obj_set_width( ui_Back_Button_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back_Button_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Back_Button_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back_Button_Label,"<-- Go Back");

lv_obj_add_event_cb(ui_Back_Button, ui_event_Back_Button, LV_EVENT_ALL, NULL);

}
