// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Selected_WP_Right_screen_init(void)
{
ui_Selected_WP_Right = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Selected_WP_Right, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Left3 = lv_label_create(ui_Selected_WP_Right);
lv_obj_set_width( ui_Left3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Left3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Left3, 0 );
lv_obj_set_y( ui_Left3, -24 );
lv_obj_set_align( ui_Left3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Left3,"Right Auton (WP) Selected");
lv_label_set_recolor(ui_Left3,"true");

ui_Back_Button4 = lv_btn_create(ui_Selected_WP_Right);
lv_obj_set_width( ui_Back_Button4, 100);
lv_obj_set_height( ui_Back_Button4, 50);
lv_obj_set_x( ui_Back_Button4, 0 );
lv_obj_set_y( ui_Back_Button4, 24 );
lv_obj_set_align( ui_Back_Button4, LV_ALIGN_CENTER );

ui_Back_Button_Label4 = lv_label_create(ui_Back_Button4);
lv_obj_set_width( ui_Back_Button_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back_Button_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Back_Button_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back_Button_Label4,"<-- Go Back");

lv_obj_add_event_cb(ui_Back_Button4, ui_event_Back_Button4, LV_EVENT_ALL, NULL);

}
