// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Autonomous_Mode_Select
void ui_Autonomous_Mode_Select_screen_init(void);
lv_obj_t *ui_Autonomous_Mode_Select;
lv_obj_t *ui_Field_Image;
lv_obj_t *ui_Blue_1;
lv_obj_t *ui_Blue_1_Label;
lv_obj_t *ui_Red_1;
lv_obj_t *ui_Red_1_Label;
lv_obj_t *ui_Blue_2;
lv_obj_t *ui_Blue_2_Label;
lv_obj_t *ui_Red_2;
lv_obj_t *ui_Red_2_Label;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Autonomous_Mode_Select_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Autonomous_Mode_Select);
}
