// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "liblvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Autonomous_Mode_Select
void ui_Autonomous_Mode_Select_screen_init(void);
extern lv_obj_t *ui_Autonomous_Mode_Select;
extern lv_obj_t *ui_Field_Image;
extern lv_obj_t *ui_Blue_1;
extern lv_obj_t *ui_Blue_1_Label;
extern lv_obj_t *ui_Red_1;
extern lv_obj_t *ui_Red_1_Label;
extern lv_obj_t *ui_Blue_2;
extern lv_obj_t *ui_Blue_2_Label;
extern lv_obj_t *ui_Red_2;
extern lv_obj_t *ui_Red_2_Label;
extern lv_obj_t *ui____initial_actions0;

extern const char *ui_img_field_png;   // assets/field.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
