// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "auton.h"

void setAutonLeft(lv_event_t * e)
{
	auton_selected = 0;
}

void setAutonRight(lv_event_t * e)
{
	auton_selected = 1;
}

void setAutonSkills(lv_event_t * e)
{
	auton_selected = 2;
}
