// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Autonomous_Mode_Select_screen_init(void)
{
ui_Autonomous_Mode_Select = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Autonomous_Mode_Select, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Field_Image = lv_img_create(ui_Autonomous_Mode_Select);
lv_img_set_src(ui_Field_Image, ui_img_field_png);
lv_obj_set_width( ui_Field_Image, LV_SIZE_CONTENT);  /// 2000
lv_obj_set_height( ui_Field_Image, LV_SIZE_CONTENT);   /// 2000
lv_obj_set_align( ui_Field_Image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Field_Image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Field_Image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Field_Image,30);

ui_Blue_1 = lv_btn_create(ui_Autonomous_Mode_Select);
lv_obj_set_width( ui_Blue_1, 100);
lv_obj_set_height( ui_Blue_1, 50);
lv_obj_set_x( ui_Blue_1, 8 );
lv_obj_set_y( ui_Blue_1, 8 );
lv_obj_set_style_bg_color(ui_Blue_1, lv_color_hex(0x1A79C3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Blue_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Blue_1_Label = lv_label_create(ui_Blue_1);
lv_obj_set_width( ui_Blue_1_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Blue_1_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Blue_1_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Blue_1_Label,"Blue 1");

ui_Red_1 = lv_btn_create(ui_Autonomous_Mode_Select);
lv_obj_set_width( ui_Red_1, 100);
lv_obj_set_height( ui_Red_1, 50);
lv_obj_set_x( ui_Red_1, -8 );
lv_obj_set_y( ui_Red_1, 8 );
lv_obj_set_align( ui_Red_1, LV_ALIGN_TOP_RIGHT );
lv_obj_set_style_bg_color(ui_Red_1, lv_color_hex(0xD72730), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Red_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Red_1_Label = lv_label_create(ui_Red_1);
lv_obj_set_width( ui_Red_1_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Red_1_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Red_1_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Red_1_Label,"Red 1");

ui_Blue_2 = lv_btn_create(ui_Autonomous_Mode_Select);
lv_obj_set_width( ui_Blue_2, 100);
lv_obj_set_height( ui_Blue_2, 50);
lv_obj_set_x( ui_Blue_2, 8 );
lv_obj_set_y( ui_Blue_2, -8 );
lv_obj_set_align( ui_Blue_2, LV_ALIGN_BOTTOM_LEFT );
lv_obj_set_style_bg_color(ui_Blue_2, lv_color_hex(0x1A79C3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Blue_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Blue_2_Label = lv_label_create(ui_Blue_2);
lv_obj_set_width( ui_Blue_2_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Blue_2_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Blue_2_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Blue_2_Label,"Blue 2");

ui_Red_2 = lv_btn_create(ui_Autonomous_Mode_Select);
lv_obj_set_width( ui_Red_2, 100);
lv_obj_set_height( ui_Red_2, 50);
lv_obj_set_x( ui_Red_2, -8 );
lv_obj_set_y( ui_Red_2, -8 );
lv_obj_set_align( ui_Red_2, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_style_bg_color(ui_Red_2, lv_color_hex(0xD72730), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Red_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Red_2_Label = lv_label_create(ui_Red_2);
lv_obj_set_width( ui_Red_2_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Red_2_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Red_2_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Red_2_Label,"Red 2");

}
