// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Selected_Skills_screen_init(void)
{
ui_Selected_Skills = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Selected_Skills, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Skills2 = lv_label_create(ui_Selected_Skills);
lv_obj_set_width( ui_Skills2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Skills2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Skills2, 0 );
lv_obj_set_y( ui_Skills2, -24 );
lv_obj_set_align( ui_Skills2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Skills2,"Skills Auton Selected");

ui_Back_Button2 = lv_btn_create(ui_Selected_Skills);
lv_obj_set_width( ui_Back_Button2, 100);
lv_obj_set_height( ui_Back_Button2, 50);
lv_obj_set_x( ui_Back_Button2, 0 );
lv_obj_set_y( ui_Back_Button2, 24 );
lv_obj_set_align( ui_Back_Button2, LV_ALIGN_CENTER );

ui_Back_Button_Label2 = lv_label_create(ui_Back_Button2);
lv_obj_set_width( ui_Back_Button_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back_Button_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Back_Button_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back_Button_Label2,"<-- Go Back");

lv_obj_add_event_cb(ui_Back_Button2, ui_event_Back_Button2, LV_EVENT_ALL, NULL);

}
