// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "auton/auton.hpp"
#include "ui.h"

void setAutonLeft(lv_event_t * e)
{
	setAutonMode(MATCH_LEFT);
}

void setAutonRight(lv_event_t * e)
{
	setAutonMode(MATCH_RIGHT);
}

void setAutonSkills(lv_event_t * e)
{
	setAutonMode(SKILLS);
}

void setAutonRightWP(lv_event_t * e)
{
	setAutonMode(MATCH_RIGHT_WP);
}

void setAutonLeftWP(lv_event_t * e)
{
	setAutonMode(MATCH_LEFT_WP);
}
